/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yvvyakgjezxphqdhyvju"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dnlha2dqZXp4cGhxZGh5dmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MjQzMTMsImV4cCI6MjA4OTMwMDMxM30.InfZj9X5NTaaS7SMfDAoAsUAqliOor-RW1m1coWgn-k"